services:
  - type: web
    name: shopin-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn shopin.wsgi:application
    build:
      python_version: 3.9.1
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: shopin.settings
    rootDir: backend
